from django.db import models

from django.http.response import JsonResponse
from django.http import HttpResponse
from django.db import connection
import pandas as pd
import seaborn as sns
import numpy as np
# import seaborn as sns


# Create your models here.
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.


class Avisorden(models.Model):
    fechacarga = models.DateTimeField()
    orden = models.CharField(max_length=10, blank=True, null=True)
    felib = models.CharField(max_length=10, blank=True, null=True)
    avisoclase = models.CharField(max_length=4, blank=True, null=True)
    aviso = models.CharField(max_length=10, blank=True, null=True)
    claot = models.CharField(max_length=4, blank=True, null=True)
    empldeno = models.CharField(max_length=20, blank=True, null=True)
    zona = models.CharField(max_length=18, blank=True, null=True)
    equipo = models.CharField(max_length=10, blank=True, null=True)
    eqdentipo = models.CharField(max_length=25, blank=True, null=True)
    eqdescrip = models.CharField(max_length=25, blank=True, null=True)
    avisodescrip = models.CharField(max_length=40, blank=True, null=True)
    repercusion = models.CharField(max_length=1, blank=True, null=True)
    cliente = models.CharField(max_length=40, blank=True, null=True)
    proyecto = models.CharField(max_length=40, blank=True, null=True)
    ave_ini_fecha = models.CharField(max_length=10, blank=True, null=True)
    ave_ini_hora = models.CharField(max_length=8, blank=True, null=True)
    ave_fin_fecha = models.CharField(max_length=10, blank=True, null=True)
    ave_fin_hora = models.CharField(max_length=8, blank=True, null=True)
    parada = models.CharField(max_length=1, blank=True, null=True)
    parada_horas = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    parada_dias = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    ubitec_deno = models.CharField(max_length=40, blank=True, null=True)
    local = models.CharField(max_length=12, blank=True, null=True)
    undneg = models.CharField(max_length=4, blank=True, null=True)
    centro_deno = models.CharField(max_length=10, blank=True, null=True)
    eq_est_usu = models.CharField(max_length=10, blank=True, null=True)
    eq_est_usu_deno = models.CharField(max_length=40, blank=True, null=True)
    flota_tipo = models.CharField(max_length=15, blank=True, null=True)
    creadopor = models.CharField(max_length=15, blank=True, null=True)
    fe_despacho = models.CharField(max_length=10, blank=True, null=True)
    orden_estsis = models.CharField(max_length=40, blank=True, null=True)
    eq_serie_motor = models.CharField(max_length=40, blank=True, null=True)
    eq_serie_equipo = models.CharField(max_length=40, blank=True, null=True)
    eq_est_ot_deno = models.CharField(max_length=30, blank=True, null=True)
    clase = models.CharField(max_length=20, blank=True, null=True)
    aviso_creadopor = models.CharField(max_length=18, blank=True, null=True)
    grupo_planif = models.CharField(max_length=3, blank=True, null=True)
    cliente_nro = models.CharField(max_length=10, blank=True, null=True)
    proyecto_nro = models.CharField(max_length=10, blank=True, null=True)
    supres_nro = models.CharField(max_length=10, blank=True, null=True)
    supres_nombre = models.CharField(max_length=30, blank=True, null=True)
    criticidad = models.CharField(max_length=1, blank=True, null=True)
    criticidad_deno = models.CharField(max_length=20, blank=True, null=True)
    orden_modife = models.CharField(max_length=10, blank=True, null=True)
    orden_modinom = models.CharField(max_length=20, blank=True, null=True)
    estado_inst = models.CharField(max_length=2, blank=True, null=True)
    eqvaloradq_usd = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    repercusiondeno = models.CharField(max_length=18, blank=True, null=True)
    oden_clase_deno = models.CharField(max_length=40, blank=True, null=True)
    costo_pla_mat = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    costo_pla_mo = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    costo_pla_ser = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    costo_real_mat = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    costo_real_mo = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    costo_real_ser = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    coti_esta_deno = models.CharField(max_length=25, blank=True, null=True)
    aviso_codi_deno = models.CharField(max_length=25, blank=True, null=True)
    avisodespacho = models.CharField(max_length=10, blank=True, null=True)
    estatususuarioorden = models.CharField(max_length=40, blank=True, null=True)
    claobj_deno = models.CharField(max_length=30, blank=True, null=True)
    claobj_nro = models.CharField(max_length=5, blank=True, null=True)
    clasif01 = models.CharField(max_length=20, blank=True, null=True)
    aviso_fecreado = models.CharField(max_length=10, blank=True, null=True)
    coti_estatus = models.CharField(max_length=2, blank=True, null=True)
    orden_fe_fin_ext = models.CharField(max_length=10, blank=True, null=True)
    orden_fe_ini_ext = models.CharField(max_length=10, blank=True, null=True)
    fabricaequipo = models.CharField(max_length=15, blank=True, null=True)
    ordenco_nro = models.CharField(max_length=10, blank=True, null=True)
    orden_fecietec = models.CharField(max_length=10, blank=True, null=True)
    horometro_fecha = models.CharField(max_length=10, blank=True, null=True)
    orden_claact = models.CharField(max_length=4, blank=True, null=True)
    orden_claact_deno = models.CharField(max_length=30, blank=True, null=True)
    libe = models.CharField(max_length=5, blank=True, null=True)
    gruplan_deno = models.CharField(max_length=20, blank=True, null=True)
    centro = models.CharField(max_length=5, blank=True, null=True)
    eq_clase = models.CharField(max_length=25, blank=True, null=True)
    orden_tipimput = models.CharField(max_length=5, blank=True, null=True)
    valorneto = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    valorpedido = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    orden_norliq = models.CharField(max_length=14, blank=True, null=True)
    orden_fecrea = models.CharField(max_length=10, blank=True, null=True)
    orden_texto = models.CharField(max_length=45, blank=True, null=True)
    orden_prio = models.CharField(max_length=2, blank=True, null=True)
    costo_pla_otros = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    costo_real_otros = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    parte_objeto = models.CharField(max_length=20, blank=True, null=True)
    ot_abierto = models.CharField(max_length=2, blank=True, null=True)
    ot_liberado = models.CharField(max_length=2, blank=True, null=True)
    ot_cierrete = models.CharField(max_length=2, blank=True, null=True)
    ot_cerrado = models.CharField(max_length=2, blank=True, null=True)
    hruta_contador = models.CharField(max_length=2, blank=True, null=True)
    hruta_grupo = models.CharField(max_length=10, blank=True, null=True)
    aviso_prioridad = models.CharField(max_length=2, blank=True, null=True)
    aviso_prioridad_deno = models.CharField(max_length=10, blank=True, null=True)
    ptotbjores_deno = models.CharField(max_length=40, blank=True, null=True)
    aviso_clase_deno = models.CharField(max_length=20, blank=True, null=True)
    aviso_codi = models.CharField(max_length=5, blank=True, null=True)
    codi = models.CharField(max_length=5, blank=True, null=True)
    aviso_autor = models.CharField(max_length=10, blank=True, null=True)
    horometro = models.CharField(max_length=12, blank=True, null=True)
    orden_revision = models.CharField(max_length=10, blank=True, null=True)
    orden_revision_texto = models.CharField(max_length=45, blank=True, null=True)
    eq_estatus_sist = models.CharField(max_length=10, blank=True, null=True)
    emplazamiento = models.CharField(max_length=5, blank=True, null=True)
    costos_total_plan = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    costos_total_real = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    eq_ubitec = models.CharField(max_length=25, blank=True, null=True)
    orden_causas_cod = models.CharField(max_length=5, blank=True, null=True)
    orden_causas = models.CharField(max_length=20, blank=True, null=True)
    orden_causas_texto = models.CharField(max_length=40, blank=True, null=True)
    orden_est_usuario = models.CharField(max_length=5, blank=True, null=True)
    valor_facturado = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    ptotbjores_cod = models.CharField(max_length=10, blank=True, null=True)
    cotizacion = models.CharField(max_length=15, blank=True, null=True)
    pedido_venta = models.CharField(max_length=15, blank=True, null=True)
    cotizacion_mon = models.CharField(max_length=5, blank=True, null=True)
    pedido_venta_mon = models.CharField(max_length=5, blank=True, null=True)
    moneda = models.CharField(max_length=5, blank=True, null=True)
    orden_pos_mtto = models.CharField(max_length=10, blank=True, null=True)
    plan_mantenimiento = models.CharField(max_length=10, blank=True, null=True)
    per_apellidonombre = models.CharField(max_length=30, blank=True, null=True)
    per_nro = models.CharField(max_length=10, blank=True, null=True)
    parte_objeto_cod = models.CharField(max_length=5, blank=True, null=True)
    parte_objeto_deno = models.CharField(max_length=20, blank=True, null=True)
    averia_texto = models.CharField(max_length=45, blank=True, null=True)
    causas_deno = models.CharField(max_length=45, blank=True, null=True)
    orden_principal = models.CharField(max_length=15, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'avisorden'


class Flota(models.Model):
    fechacarga = models.DateTimeField()
    equipo = models.CharField(max_length=10, blank=True, null=True)
    categoria = models.CharField(max_length=45, blank=True, null=True)
    tpobjeto = models.CharField(max_length=10, blank=True, null=True)
    desclaobjeto = models.CharField(max_length=20, blank=True, null=True)
    fabricante = models.CharField(max_length=30, blank=True, null=True)
    modelo = models.CharField(max_length=20, blank=True, null=True)
    nseriemotor = models.CharField(max_length=20, blank=True, null=True)
    nseriefabri = models.CharField(max_length=30, blank=True, null=True)
    materiallog = models.CharField(max_length=30, blank=True, null=True)
    materiallogdescrip = models.CharField(max_length=40, blank=True, null=True)
    codpais = models.CharField(max_length=2, blank=True, null=True)
    despaisfabricante = models.CharField(max_length=30, blank=True, null=True)
    anoconstruccion = models.CharField(max_length=4, blank=True, null=True)
    mesconstruccion = models.CharField(max_length=2, blank=True, null=True)
    ptomedida = models.CharField(max_length=5, blank=True, null=True)
    ultimodocmed = models.CharField(max_length=5, blank=True, null=True)
    fechaulthoro = models.CharField(max_length=10, blank=True, null=True)
    ulthoro = models.DecimalField(max_digits=9, decimal_places=2, blank=True, null=True)
    acuhoro = models.DecimalField(max_digits=9, decimal_places=2, blank=True, null=True)
    valcondesp = models.CharField(max_length=10, blank=True, null=True)
    avisodesp = models.CharField(max_length=10, blank=True, null=True)
    fedespa = models.CharField(max_length=10, blank=True, null=True)
    hodespa = models.CharField(max_length=8, blank=True, null=True)
    valconrece = models.CharField(max_length=10, blank=True, null=True)
    avisorece = models.CharField(max_length=10, blank=True, null=True)
    fecharece = models.CharField(max_length=10, blank=True, null=True)
    horarece = models.CharField(max_length=8, blank=True, null=True)
    disiregco = models.IntegerField(blank=True, null=True)
    feregcrea = models.CharField(max_length=10, blank=True, null=True)
    ceempl = models.CharField(max_length=4, blank=True, null=True)
    ceemplnombre = models.CharField(max_length=20, blank=True, null=True)
    ceemplregion = models.CharField(max_length=4, blank=True, null=True)
    ceemplzona = models.CharField(max_length=15, blank=True, null=True)
    nper = models.CharField(max_length=10, blank=True, null=True)
    nperapellido = models.CharField(max_length=40, blank=True, null=True)
    activofijo = models.CharField(max_length=15, blank=True, null=True)
    subnumero = models.CharField(max_length=15, blank=True, null=True)
    identific = models.CharField(max_length=15, blank=True, null=True)
    linegcod = models.CharField(max_length=4, blank=True, null=True)
    linegnombre = models.CharField(max_length=20, blank=True, null=True)
    indabc = models.CharField(max_length=1, blank=True, null=True)
    indabcnombre = models.CharField(max_length=20, blank=True, null=True)
    estadoequ = models.CharField(max_length=10, blank=True, null=True)
    estatusequ = models.CharField(max_length=40, blank=True, null=True)
    estatussist = models.CharField(max_length=10, blank=True, null=True)
    estatussistdeno = models.CharField(max_length=60, blank=True, null=True)
    feultestatus = models.CharField(max_length=10, blank=True, null=True)
    proycod = models.CharField(max_length=15, blank=True, null=True)
    proydesc = models.CharField(max_length=45, blank=True, null=True)
    clicod = models.CharField(max_length=15, blank=True, null=True)
    clidesc = models.CharField(max_length=45, blank=True, null=True)
    valadq = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    moneda = models.CharField(max_length=4, blank=True, null=True)
    fechaadq = models.CharField(max_length=10, blank=True, null=True)
    equsuperior = models.CharField(max_length=10, blank=True, null=True)
    equsuperiordeno = models.CharField(max_length=30, blank=True, null=True)
    ubitec = models.CharField(max_length=20, blank=True, null=True)
    ubitecdeno = models.CharField(max_length=45, blank=True, null=True)
    estadogar = models.CharField(max_length=15, blank=True, null=True)
    feestfingar = models.CharField(max_length=10, blank=True, null=True)
    fegar = models.CharField(max_length=10, blank=True, null=True)
    fefingar = models.CharField(max_length=10, blank=True, null=True)
    categoriaid = models.CharField(max_length=1, blank=True, null=True)
    denotipequ = models.CharField(max_length=30, blank=True, null=True)
    local = models.CharField(max_length=10, blank=True, null=True)
    codintequ = models.CharField(max_length=10, blank=True, null=True)
    grupla = models.CharField(max_length=5, blank=True, null=True)
    grupladesc = models.CharField(max_length=20, blank=True, null=True)
    ordliq = models.CharField(max_length=20, blank=True, null=True)
    ordliqdesc = models.CharField(max_length=45, blank=True, null=True)
    tipmon = models.CharField(max_length=20, blank=True, null=True)
    tipmondeno = models.CharField(max_length=45, blank=True, null=True)
    nroinv = models.CharField(max_length=10, blank=True, null=True)
    ceco = models.CharField(max_length=10, blank=True, null=True)
    cecodeno = models.CharField(max_length=20, blank=True, null=True)
    cepla = models.CharField(max_length=4, blank=True, null=True)
    ceplanomb = models.CharField(max_length=20, blank=True, null=True)
    idtecnica = models.CharField(max_length=10, blank=True, null=True)
    peso = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    pesound = models.CharField(max_length=4, blank=True, null=True)
    fabricanteid = models.CharField(max_length=3, blank=True, null=True)
    fabrica = models.CharField(max_length=40, blank=True, null=True)
    jerprocod = models.CharField(max_length=20, blank=True, null=True)
    jerprocoddeno = models.CharField(max_length=50, blank=True, null=True)
    marcaid = models.CharField(max_length=5, blank=True, null=True)
    marcadeno = models.CharField(max_length=20, blank=True, null=True)
    cateid = models.CharField(max_length=10, blank=True, null=True)
    catedeno = models.CharField(max_length=30, blank=True, null=True)
    eqmod = models.CharField(max_length=10, blank=True, null=True)
    eqmoddeno = models.CharField(max_length=30, blank=True, null=True)
    linea = models.CharField(max_length=2, blank=True, null=True)
    lineadeno = models.CharField(max_length=30, blank=True, null=True)
    submarca = models.CharField(max_length=5, blank=True, null=True)
    submarcadeno = models.CharField(max_length=20, blank=True, null=True)
    grupoart = models.CharField(max_length=6, blank=True, null=True)
    grupoartdeno = models.CharField(max_length=30, blank=True, null=True)
    sector = models.CharField(max_length=2, blank=True, null=True)
    lineadeno2 = models.CharField(max_length=30, blank=True, null=True)
    codmark = models.CharField(max_length=10, blank=True, null=True)
    denosubmarca = models.CharField(max_length=20, blank=True, null=True)
    perfilcata = models.CharField(max_length=10, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'flota'


class InventarioS4(models.Model):
    fechacarga = models.DateTimeField()
    centro = models.CharField(max_length=4, blank=True, null=True)
    centronombre = models.CharField(max_length=20, blank=True, null=True)
    alm = models.CharField(max_length=4, blank=True, null=True)
    almnombre = models.CharField(max_length=20, blank=True, null=True)
    material = models.CharField(max_length=20, blank=True, null=True)
    materialtxt = models.CharField(max_length=50, blank=True, null=True)
    cantidad = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    unidades = models.CharField(max_length=5, blank=True, null=True)
    valorpen = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    moneda = models.CharField(max_length=5, blank=True, null=True)
    clasevalor = models.CharField(max_length=20, blank=True, null=True)
    ubicacion = models.CharField(max_length=20, blank=True, null=True)
    tras_cant = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    tras_valor = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    insp_cant = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    insp_valor = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    stknolibre_cant = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    stknolibre_valor = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    bloq_cant = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    bloq_valor = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    dev_cant = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    dev_valor = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    fabricante = models.CharField(max_length=40, blank=True, null=True)
    marca = models.CharField(max_length=40, blank=True, null=True)
    modelo = models.CharField(max_length=40, blank=True, null=True)
    subtipo = models.CharField(max_length=40, blank=True, null=True)
    presentacion = models.CharField(max_length=40, blank=True, null=True)
    grart_ext = models.CharField(max_length=20, blank=True, null=True)
    tipomaterial = models.CharField(max_length=10, blank=True, null=True)
    grupoarticulo = models.CharField(max_length=10, blank=True, null=True)
    stkbloqem_cant = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    stkbloqem_valor = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    stkenvaslig_cant = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    stkenvaslig_valor = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    stktrans_cant = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    stktrans_valor = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    stktrasl_cant = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    stktrasl_valor = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'inventario_s4'


class Ordenreserva(models.Model):
    id = models.IntegerField(primary_key=True)
    fechacarga = models.DateTimeField(blank=True, null=True)
    orden = models.CharField(max_length=10, blank=True, null=True)
    felib = models.CharField(max_length=10, blank=True, null=True)
    aviso = models.CharField(max_length=10, blank=True, null=True)
    empldeno = models.CharField(max_length=20, blank=True, null=True)
    zona = models.CharField(max_length=18, blank=True, null=True)
    equipo = models.CharField(max_length=10, blank=True, null=True)
    eqdescrip = models.CharField(max_length=25, blank=True, null=True)
    repercusion = models.CharField(max_length=1, blank=True, null=True)
    cliente = models.CharField(max_length=40, blank=True, null=True)
    proyecto = models.CharField(max_length=40, blank=True, null=True)
    ave_ini_fecha = models.CharField(max_length=10, blank=True, null=True)
    ave_fin_fecha = models.CharField(max_length=10, blank=True, null=True)
    parada = models.CharField(max_length=1, blank=True, null=True)
    parada_dias = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    ubitec_deno = models.CharField(max_length=40, blank=True, null=True)
    local = models.CharField(max_length=12, blank=True, null=True)
    undneg = models.CharField(max_length=4, blank=True, null=True)
    centro_deno = models.CharField(max_length=10, blank=True, null=True)
    eq_est_usu_deno = models.CharField(max_length=40, blank=True, null=True)
    flota_tipo = models.CharField(max_length=15, blank=True, null=True)
    fe_despacho = models.CharField(max_length=10, blank=True, null=True)
    eq_serie_motor = models.CharField(max_length=40, blank=True, null=True)
    eq_serie_equipo = models.CharField(max_length=40, blank=True, null=True)
    eq_est_ot_deno = models.CharField(max_length=30, blank=True, null=True)
    clase = models.CharField(max_length=20, blank=True, null=True)
    grupo_planif = models.CharField(max_length=3, blank=True, null=True)
    cliente_nro = models.CharField(max_length=10, blank=True, null=True)
    proyecto_nro = models.CharField(max_length=10, blank=True, null=True)
    supres_nombre = models.CharField(max_length=30, blank=True, null=True)
    criticidad_deno = models.CharField(max_length=20, blank=True, null=True)
    eqvaloradq_usd = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    repercusiondeno = models.CharField(max_length=18, blank=True, null=True)
    oden_clase_deno = models.CharField(max_length=40, blank=True, null=True)
    coti_esta_deno = models.CharField(max_length=25, blank=True, null=True)
    avisodespacho = models.CharField(max_length=10, blank=True, null=True)
    estatususuarioorden = models.CharField(max_length=40, blank=True, null=True)
    aviso_fecreado = models.CharField(max_length=10, blank=True, null=True)
    orden_fe_fin_ext = models.CharField(max_length=10, blank=True, null=True)
    orden_fe_ini_ext = models.CharField(max_length=10, blank=True, null=True)
    fabricaequipo = models.CharField(max_length=15, blank=True, null=True)
    orden_fecietec = models.CharField(max_length=10, blank=True, null=True)
    orden_claact_deno = models.CharField(max_length=30, blank=True, null=True)
    gruplan_deno = models.CharField(max_length=20, blank=True, null=True)
    centro = models.CharField(max_length=5, blank=True, null=True)
    eq_clase = models.CharField(max_length=25, blank=True, null=True)
    orden_tipimput = models.CharField(max_length=5, blank=True, null=True)
    orden_fecrea = models.CharField(max_length=10, blank=True, null=True)
    orden_texto = models.CharField(max_length=45, blank=True, null=True)
    orden_prio = models.CharField(max_length=2, blank=True, null=True)
    ot_abierto = models.CharField(max_length=2, blank=True, null=True)
    ot_liberado = models.CharField(max_length=2, blank=True, null=True)
    ot_cierrete = models.CharField(max_length=2, blank=True, null=True)
    ot_cerrado = models.CharField(max_length=2, blank=True, null=True)
    hruta_contador = models.CharField(max_length=2, blank=True, null=True)
    hruta_grupo = models.CharField(max_length=10, blank=True, null=True)
    aviso_prioridad_deno = models.CharField(max_length=10, blank=True, null=True)
    aviso_clase_deno = models.CharField(max_length=20, blank=True, null=True)
    orden_revision = models.CharField(max_length=10, blank=True, null=True)
    orden_revision_texto = models.CharField(max_length=45, blank=True, null=True)
    orden_causas_cod = models.CharField(max_length=5, blank=True, null=True)
    orden_causas = models.CharField(max_length=20, blank=True, null=True)
    orden_causas_texto = models.CharField(max_length=40, blank=True, null=True)
    cotizacion = models.CharField(max_length=15, blank=True, null=True)
    pedido_venta = models.CharField(max_length=15, blank=True, null=True)
    orden_pos_mtto = models.CharField(max_length=10, blank=True, null=True)
    plan_mantenimiento = models.CharField(max_length=10, blank=True, null=True)
    reserva_fechacarga = models.DateTimeField(blank=True, null=True)
    reserva = models.CharField(max_length=10, blank=True, null=True)
    reservapos = models.CharField(max_length=6, blank=True, null=True)
    material = models.CharField(max_length=20, blank=True, null=True)
    materialdeno = models.CharField(max_length=45, blank=True, null=True)
    ctd_nec = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    ctd_reduc = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    ctd_dif = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    um_base = models.CharField(max_length=4, blank=True, null=True)
    usuario = models.CharField(max_length=18, blank=True, null=True)
    reserva_centro = models.CharField(max_length=5, blank=True, null=True)
    reserva_almacen = models.CharField(max_length=5, blank=True, null=True)
    lote = models.CharField(max_length=10, blank=True, null=True)
    fe_nece = models.CharField(max_length=10, blank=True, null=True)
    orden_op = models.CharField(max_length=4, blank=True, null=True)
    dest_merc = models.CharField(max_length=18, blank=True, null=True)
    imputacion = models.CharField(max_length=12, blank=True, null=True)
    ce_coste = models.CharField(max_length=10, blank=True, null=True)
    salida_fin = models.CharField(max_length=2, blank=True, null=True)
    relevplnec = models.CharField(max_length=2, blank=True, null=True)
    grafo = models.CharField(max_length=10, blank=True, null=True)
    elem_pep = models.CharField(max_length=10, blank=True, null=True)
    febase = models.CharField(max_length=10, blank=True, null=True)
    reservaestatus = models.CharField(max_length=10, blank=True, null=True)
    reservaimputacion = models.CharField(max_length=2, blank=True, null=True)
    indicador_dh = models.CharField(max_length=2, blank=True, null=True)
    reserva_pos_borrado = models.CharField(max_length=2, blank=True, null=True)
    reserva_mov_permit = models.CharField(max_length=2, blank=True, null=True)
    ate_codigosap = models.CharField(max_length=20, blank=True, null=True)
    ate_cantidad = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    ate_umb = models.CharField(db_column='ate_UMB', max_length=4, blank=True, null=True)  # Field name made lowercase.
    ate_orden = models.IntegerField(blank=True, null=True)
    ate_fecha = models.DateField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'ordenreserva'


class PlanAvisorden(models.Model):
    id = models.IntegerField(primary_key=True)
    fechacarga = models.DateTimeField()
    orden = models.CharField(max_length=10, blank=True, null=True)
    felib = models.CharField(max_length=10, blank=True, null=True)
    aviso = models.CharField(max_length=10, blank=True, null=True)
    empldeno = models.CharField(max_length=20, blank=True, null=True)
    zona = models.CharField(max_length=18, blank=True, null=True)
    equipo = models.CharField(max_length=10, blank=True, null=True)
    eqdescrip = models.CharField(max_length=25, blank=True, null=True)
    repercusion = models.CharField(max_length=1, blank=True, null=True)
    cliente = models.CharField(max_length=40, blank=True, null=True)
    proyecto = models.CharField(max_length=40, blank=True, null=True)
    ave_ini_fecha = models.CharField(max_length=10, blank=True, null=True)
    ave_fin_fecha = models.CharField(max_length=10, blank=True, null=True)
    parada = models.CharField(max_length=1, blank=True, null=True)
    parada_dias = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    ubitec_deno = models.CharField(max_length=40, blank=True, null=True)
    local = models.CharField(max_length=12, blank=True, null=True)
    undneg = models.CharField(max_length=4, blank=True, null=True)
    centro_deno = models.CharField(max_length=10, blank=True, null=True)
    eq_est_usu_deno = models.CharField(max_length=40, blank=True, null=True)
    flota_tipo = models.CharField(max_length=15, blank=True, null=True)
    fe_despacho = models.CharField(max_length=10, blank=True, null=True)
    eq_serie_motor = models.CharField(max_length=40, blank=True, null=True)
    eq_serie_equipo = models.CharField(max_length=40, blank=True, null=True)
    eq_est_ot_deno = models.CharField(max_length=30, blank=True, null=True)
    clase = models.CharField(max_length=20, blank=True, null=True)
    grupo_planif = models.CharField(max_length=3, blank=True, null=True)
    cliente_nro = models.CharField(max_length=10, blank=True, null=True)
    proyecto_nro = models.CharField(max_length=10, blank=True, null=True)
    supres_nombre = models.CharField(max_length=30, blank=True, null=True)
    criticidad_deno = models.CharField(max_length=20, blank=True, null=True)
    eqvaloradq_usd = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    repercusiondeno = models.CharField(max_length=18, blank=True, null=True)
    oden_clase_deno = models.CharField(max_length=40, blank=True, null=True)
    coti_esta_deno = models.CharField(max_length=25, blank=True, null=True)
    avisodespacho = models.CharField(max_length=10, blank=True, null=True)
    estatususuarioorden = models.CharField(max_length=40, blank=True, null=True)
    aviso_fecreado = models.CharField(max_length=10, blank=True, null=True)
    orden_fe_fin_ext = models.CharField(max_length=10, blank=True, null=True)
    orden_fe_ini_ext = models.CharField(max_length=10, blank=True, null=True)
    fabricaequipo = models.CharField(max_length=15, blank=True, null=True)
    orden_fecietec = models.CharField(max_length=10, blank=True, null=True)
    orden_claact_deno = models.CharField(max_length=30, blank=True, null=True)
    gruplan_deno = models.CharField(max_length=20, blank=True, null=True)
    centro = models.CharField(max_length=5, blank=True, null=True)
    eq_clase = models.CharField(max_length=25, blank=True, null=True)
    orden_tipimput = models.CharField(max_length=5, blank=True, null=True)
    orden_fecrea = models.CharField(max_length=10, blank=True, null=True)
    orden_texto = models.CharField(max_length=45, blank=True, null=True)
    orden_prio = models.CharField(max_length=2, blank=True, null=True)
    ot_abierto = models.CharField(max_length=2, blank=True, null=True)
    ot_liberado = models.CharField(max_length=2, blank=True, null=True)
    ot_cierrete = models.CharField(max_length=2, blank=True, null=True)
    ot_cerrado = models.CharField(max_length=2, blank=True, null=True)
    hruta_contador = models.CharField(max_length=2, blank=True, null=True)
    hruta_grupo = models.CharField(max_length=10, blank=True, null=True)
    aviso_prioridad_deno = models.CharField(max_length=10, blank=True, null=True)
    aviso_clase_deno = models.CharField(max_length=20, blank=True, null=True)
    orden_revision = models.CharField(max_length=10, blank=True, null=True)
    orden_revision_texto = models.CharField(max_length=45, blank=True, null=True)
    orden_causas_cod = models.CharField(max_length=5, blank=True, null=True)
    orden_causas = models.CharField(max_length=20, blank=True, null=True)
    orden_causas_texto = models.CharField(max_length=40, blank=True, null=True)
    cotizacion = models.CharField(max_length=15, blank=True, null=True)
    pedido_venta = models.CharField(max_length=15, blank=True, null=True)
    orden_pos_mtto = models.CharField(max_length=10, blank=True, null=True)
    plan_mantenimiento = models.CharField(max_length=10, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'plan_avisorden'


class PlanOrdenreserva(models.Model):
    id = models.IntegerField(primary_key=True)
    fechacarga = models.DateTimeField(blank=True, null=True)
    orden = models.CharField(max_length=10, blank=True, null=True)
    felib = models.CharField(max_length=10, blank=True, null=True)
    aviso = models.CharField(max_length=10, blank=True, null=True)
    empldeno = models.CharField(max_length=20, blank=True, null=True)
    zona = models.CharField(max_length=18, blank=True, null=True)
    equipo = models.CharField(max_length=10, blank=True, null=True)
    eqdescrip = models.CharField(max_length=25, blank=True, null=True)
    repercusion = models.CharField(max_length=1, blank=True, null=True)
    cliente = models.CharField(max_length=40, blank=True, null=True)
    proyecto = models.CharField(max_length=40, blank=True, null=True)
    ave_ini_fecha = models.CharField(max_length=10, blank=True, null=True)
    ave_fin_fecha = models.CharField(max_length=10, blank=True, null=True)
    parada = models.CharField(max_length=1, blank=True, null=True)
    parada_dias = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    ubitec_deno = models.CharField(max_length=40, blank=True, null=True)
    local = models.CharField(max_length=12, blank=True, null=True)
    undneg = models.CharField(max_length=4, blank=True, null=True)
    centro_deno = models.CharField(max_length=10, blank=True, null=True)
    eq_est_usu_deno = models.CharField(max_length=40, blank=True, null=True)
    flota_tipo = models.CharField(max_length=15, blank=True, null=True)
    fe_despacho = models.CharField(max_length=10, blank=True, null=True)
    eq_serie_motor = models.CharField(max_length=40, blank=True, null=True)
    eq_serie_equipo = models.CharField(max_length=40, blank=True, null=True)
    eq_est_ot_deno = models.CharField(max_length=30, blank=True, null=True)
    clase = models.CharField(max_length=20, blank=True, null=True)
    grupo_planif = models.CharField(max_length=3, blank=True, null=True)
    cliente_nro = models.CharField(max_length=10, blank=True, null=True)
    proyecto_nro = models.CharField(max_length=10, blank=True, null=True)
    supres_nombre = models.CharField(max_length=30, blank=True, null=True)
    criticidad_deno = models.CharField(max_length=20, blank=True, null=True)
    eqvaloradq_usd = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    repercusiondeno = models.CharField(max_length=18, blank=True, null=True)
    oden_clase_deno = models.CharField(max_length=40, blank=True, null=True)
    coti_esta_deno = models.CharField(max_length=25, blank=True, null=True)
    avisodespacho = models.CharField(max_length=10, blank=True, null=True)
    estatususuarioorden = models.CharField(max_length=40, blank=True, null=True)
    aviso_fecreado = models.CharField(max_length=10, blank=True, null=True)
    orden_fe_fin_ext = models.CharField(max_length=10, blank=True, null=True)
    orden_fe_ini_ext = models.CharField(max_length=10, blank=True, null=True)
    fabricaequipo = models.CharField(max_length=15, blank=True, null=True)
    orden_fecietec = models.CharField(max_length=10, blank=True, null=True)
    orden_claact_deno = models.CharField(max_length=30, blank=True, null=True)
    gruplan_deno = models.CharField(max_length=20, blank=True, null=True)
    centro = models.CharField(max_length=5, blank=True, null=True)
    eq_clase = models.CharField(max_length=25, blank=True, null=True)
    orden_tipimput = models.CharField(max_length=5, blank=True, null=True)
    orden_fecrea = models.CharField(max_length=10, blank=True, null=True)
    orden_texto = models.CharField(max_length=45, blank=True, null=True)
    orden_prio = models.CharField(max_length=2, blank=True, null=True)
    ot_abierto = models.CharField(max_length=2, blank=True, null=True)
    ot_liberado = models.CharField(max_length=2, blank=True, null=True)
    ot_cierrete = models.CharField(max_length=2, blank=True, null=True)
    ot_cerrado = models.CharField(max_length=2, blank=True, null=True)
    hruta_contador = models.CharField(max_length=2, blank=True, null=True)
    hruta_grupo = models.CharField(max_length=10, blank=True, null=True)
    aviso_prioridad_deno = models.CharField(max_length=10, blank=True, null=True)
    aviso_clase_deno = models.CharField(max_length=20, blank=True, null=True)
    orden_revision = models.CharField(max_length=10, blank=True, null=True)
    orden_revision_texto = models.CharField(max_length=45, blank=True, null=True)
    orden_causas_cod = models.CharField(max_length=5, blank=True, null=True)
    orden_causas = models.CharField(max_length=20, blank=True, null=True)
    orden_causas_texto = models.CharField(max_length=40, blank=True, null=True)
    cotizacion = models.CharField(max_length=15, blank=True, null=True)
    pedido_venta = models.CharField(max_length=15, blank=True, null=True)
    orden_pos_mtto = models.CharField(max_length=10, blank=True, null=True)
    plan_mantenimiento = models.CharField(max_length=10, blank=True, null=True)
    reserva_fechacarga = models.DateTimeField(blank=True, null=True)
    reserva = models.CharField(max_length=10, blank=True, null=True)
    reservapos = models.CharField(max_length=6, blank=True, null=True)
    material = models.CharField(max_length=20, blank=True, null=True)
    materialdeno = models.CharField(max_length=45, blank=True, null=True)
    ctd_nec = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    ctd_reduc = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    ctd_dif = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    um_base = models.CharField(max_length=4, blank=True, null=True)
    usuario = models.CharField(max_length=18, blank=True, null=True)
    reserva_centro = models.CharField(max_length=5, blank=True, null=True)
    reserva_almacen = models.CharField(max_length=5, blank=True, null=True)
    lote = models.CharField(max_length=10, blank=True, null=True)
    fe_nece = models.CharField(max_length=10, blank=True, null=True)
    orden_op = models.CharField(max_length=4, blank=True, null=True)
    dest_merc = models.CharField(max_length=18, blank=True, null=True)
    imputacion = models.CharField(max_length=12, blank=True, null=True)
    ce_coste = models.CharField(max_length=10, blank=True, null=True)
    salida_fin = models.CharField(max_length=2, blank=True, null=True)
    relevplnec = models.CharField(max_length=2, blank=True, null=True)
    grafo = models.CharField(max_length=10, blank=True, null=True)
    elem_pep = models.CharField(max_length=10, blank=True, null=True)
    febase = models.CharField(max_length=10, blank=True, null=True)
    reservaestatus = models.CharField(max_length=10, blank=True, null=True)
    reservaimputacion = models.CharField(max_length=2, blank=True, null=True)
    indicador_dh = models.CharField(max_length=2, blank=True, null=True)
    reserva_pos_borrado = models.CharField(max_length=2, blank=True, null=True)
    reserva_mov_permit = models.CharField(max_length=2, blank=True, null=True)
    ate_accion = models.CharField(max_length=10, blank=True, null=True)
    ate_codigosap = models.CharField(max_length=20, blank=True, null=True)
    ate_cantidad = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    ate_umb = models.CharField(db_column='ate_UMB', max_length=4, blank=True, null=True)  # Field name made lowercase.
    ate_orden = models.IntegerField(blank=True, null=True)
    ate_fecha = models.DateField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'plan_ordenreserva'


class PlanReservas(models.Model):
    id = models.IntegerField(primary_key=True)
    fechacarga = models.DateTimeField()
    reserva = models.CharField(max_length=10, blank=True, null=True)
    reservapos = models.CharField(max_length=6, blank=True, null=True)
    material = models.CharField(max_length=20, blank=True, null=True)
    materialdeno = models.CharField(max_length=45, blank=True, null=True)
    ctd_nec = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    ctd_reduc = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    ctd_dif = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    um_base = models.CharField(max_length=4, blank=True, null=True)
    orden = models.CharField(max_length=12, blank=True, null=True)
    usuario = models.CharField(max_length=18, blank=True, null=True)
    centro = models.CharField(max_length=5, blank=True, null=True)
    almacen = models.CharField(max_length=5, blank=True, null=True)
    lote = models.CharField(max_length=10, blank=True, null=True)
    fe_nece = models.CharField(max_length=10, blank=True, null=True)
    orden_op = models.CharField(max_length=4, blank=True, null=True)
    dest_merc = models.CharField(max_length=18, blank=True, null=True)
    imputacion = models.CharField(max_length=12, blank=True, null=True)
    ce_coste = models.CharField(max_length=10, blank=True, null=True)
    salida_fin = models.CharField(max_length=2, blank=True, null=True)
    relevplnec = models.CharField(max_length=2, blank=True, null=True)
    grafo = models.CharField(max_length=10, blank=True, null=True)
    elem_pep = models.CharField(max_length=10, blank=True, null=True)
    febase = models.CharField(max_length=10, blank=True, null=True)
    reservaestatus = models.CharField(max_length=10, blank=True, null=True)
    reservaimputacion = models.CharField(max_length=2, blank=True, null=True)
    indicador_dh = models.CharField(max_length=2, blank=True, null=True)
    reserva_pos_borrado = models.CharField(max_length=2, blank=True, null=True)
    reserva_mov_permit = models.CharField(max_length=2, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'plan_reservas'


class Reservas(models.Model):
    fechacarga = models.DateTimeField()
    reserva = models.CharField(max_length=10, blank=True, null=True)
    reservapos = models.CharField(max_length=6, blank=True, null=True)
    material = models.CharField(max_length=20, blank=True, null=True)
    materialdeno = models.CharField(max_length=45, blank=True, null=True)
    ctd_nec = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    ctd_reduc = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    ctd_dif = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    um_base = models.CharField(max_length=4, blank=True, null=True)
    orden = models.CharField(max_length=12, blank=True, null=True)
    usuario = models.CharField(max_length=18, blank=True, null=True)
    centro = models.CharField(max_length=5, blank=True, null=True)
    almacen = models.CharField(max_length=5, blank=True, null=True)
    lote = models.CharField(max_length=10, blank=True, null=True)
    fe_nece = models.CharField(max_length=10, blank=True, null=True)
    orden_op = models.CharField(max_length=4, blank=True, null=True)
    clasemov = models.CharField(max_length=4, blank=True, null=True)
    clasemovtxt = models.CharField(max_length=15, blank=True, null=True)
    dest_merc = models.CharField(max_length=18, blank=True, null=True)
    clasenec = models.CharField(max_length=3, blank=True, null=True)
    clasereg = models.CharField(max_length=5, blank=True, null=True)
    imputacion = models.CharField(max_length=12, blank=True, null=True)
    act_fijo = models.CharField(max_length=18, blank=True, null=True)
    sub_numero = models.CharField(max_length=10, blank=True, null=True)
    pos_dummy = models.CharField(max_length=10, blank=True, null=True)
    um_entrada = models.CharField(max_length=4, blank=True, null=True)
    ctd_entrada = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    pedidocliente = models.CharField(max_length=10, blank=True, null=True)
    pedidocliente_rep = models.CharField(max_length=10, blank=True, null=True)
    pedidocliente_pos = models.CharField(max_length=10, blank=True, null=True)
    ce_coste = models.CharField(max_length=10, blank=True, null=True)
    salida_fin = models.CharField(max_length=2, blank=True, null=True)
    relevplnec = models.CharField(max_length=2, blank=True, null=True)
    grafo = models.CharField(max_length=10, blank=True, null=True)
    elem_pep = models.CharField(max_length=10, blank=True, null=True)
    ctd_pos_tm_nec = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    febase = models.CharField(max_length=10, blank=True, null=True)
    reservaestatus = models.CharField(max_length=10, blank=True, null=True)
    reservaimputacion = models.CharField(max_length=2, blank=True, null=True)
    matgrn = models.CharField(max_length=20, blank=True, null=True)
    segm_stock = models.CharField(max_length=10, blank=True, null=True)
    indicador_dh = models.CharField(max_length=2, blank=True, null=True)
    stock_esp = models.CharField(max_length=2, blank=True, null=True)
    receptor_alm = models.CharField(max_length=5, blank=True, null=True)
    receptor_centro = models.CharField(max_length=5, blank=True, null=True)
    ctd_ver_disp = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    reserva_pos_borrado = models.CharField(max_length=2, blank=True, null=True)
    reserva_mov_permit = models.CharField(max_length=2, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'reservas'


class Planeamiento(models.Model):
    def limpiar_planordenreserva(request):
        borrado = False
        try:
            with connection.cursor() as cursor:
                cursor.callproc('abastece_limpia_ordenreservas')
                borrado = True
        except Exception as error:
            borrado = False
        return borrado

    def limpiar_tablasplan(request):
        borrado = False
        try:
            with connection.cursor() as cursor:
            
                cursor.callproc('limpieza_tablas_plan')
                borrado = True
        except Exception as error:
            borrado = False
        return borrado    
    
    def crear_planreservas(request):
        creado = False
        try:
            with connection.cursor() as cursor:
                    cursor.callproc('abastece_planreservas')
                    creado = True
        except Exception as error:
            creado = False                
        return creado
    
    def crear_planavisorden(request):
        creado = False
        try:
            with connection.cursor() as cursor:
                    cursor.callproc('abastece_planavisorden')
                    creado = True
        except Exception as error:
            creado = False                
        return creado

